language: php

# notifications:
#   email:
#     on_success: never
#     on_failure: change

branches:
  only:
    - master

sudo: false

env:
  global:
    - GIT_COMMITTER_NAME=travis-ci
    - GIT_COMMITTER_EMAIL=kurudrive@gmail.com
    - GIT_AUTHOR_NAME=travis-ci
    - GIT_AUTHOR_EMAIL=kurudrive@gmail.com
    - secure: "aWJdffzNl07iD2XwqzIbc/6F/PHzJEUvaMI3Qu3NXzdSHl+W7B1jp5ADPLxhr7g+/mdIkYvVErERaqRs+BAu/z4VbaqxYLCiV1bJPQfyobrSYNHpWuIe9TcNPe9/6OdiumTtPjIaQsp/brAHs7dGJbJOXPLaf16xvUyZCaGgqmu65VdWy0B6pMb5v+ta2NqBVd5/uQbsep5opmIBzNSWDWNIP26x4fTEu5DZE9NvnmUqLqJCEnqePhr8xUXVrH26m4uueZ2kC1Vey67BIwc4nSSei0lwE1Ql3YbCTxe7REh5PKI9cjLes27QuLnJqWcTA9sBWqt/YH6hHSQFe6SCobDhDLPE0ft7WOanMDTAKKptEa0FzZXpZBFTGctw/IgyUL8GDUcJZ3vKUVGSoV0JFdIf2ZZa9zbP9Q5i3v/ZY8uzVh4EtezMp1Sjfx/zT7r71rYsdYo6gttI0qKS6TZ3RPROMNJwCBM7kLZMvGHniAAoHY2icNUpoxYO48297vJSE2NUP/dVZSq56OpOMzdKCx5dnmKRgPOm9fFFEzLmTi29/VeKNEnsQxVgmZ9RqSvFUzlQ/f74KGcElcpf22WEC2r/ah2VMJJuRJZqAlOwihf6XJvBURerji1gwAEet2+Xb6VYAMGMyfX6kuo/V2cyYfTAmeZoqnrtd79DCKHTcD0="

matrix:
  include:
    - php: 7.3
      dist: trusty
      env:
        - WP_VERSION=latest WP_MULTISITE=0
    - php: 7.2
      dist: trusty
      env:
        - WP_VERSION=latest WP_MULTISITE=0
        - WP_VERSION=latest WP_MULTISITE=1
        - WP_VERSION=4.4 WP_MULTISITE=0
    # - php: 7.1
    #   env:
    #     - WP_VERSION=latest WP_MULTISITE=0
    # - php: 7
    #   env:
    #     - WP_VERSION=latest WP_MULTISITE=0
    #     # - WP_VERSION=latest WP_MULTISITE=1
    # - php: 5.6
    #   env:
    #     - WP_VERSION=latest WP_MULTISITE=0
    #     - WP_VERSION=latest WP_MULTISITE=1
    #     - WP_VERSION=4.4 WP_MULTISITE=0
        # - WP_VERSION=4.7.5 WP_MULTISITE=0

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - echo ${TRAVIS_PHP_VERSION:0:3}
  - |
    if [[ ${TRAVIS_PHP_VERSION:0:3} =~ 7\.[0-1] ]]; then
      composer global require "phpunit/phpunit=6.*.*"
    elif [[ ${TRAVIS_PHP_VERSION:0:3} == "5.6" ]]; then
      composer global require "phpunit/phpunit=5.*.*"
    else
      composer global require "phpunit/phpunit=4.8.*"
    fi
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.2" ]]; then composer install; fi

  - nvm install 4.2
  - npm install

script:
#   # - phpcs --standard=phpcs.ruleset.xml $(find . -name '*.php')
  - find ./ -name '*.php'|xargs -I {} php -l {}
  - phpunit --version
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.2" ]]; then ./vendor/bin/phpunit; else phpunit; fi
  - phpunit

after_success:
  - bash ./bin/deploy.sh
